---
- name: Install IIS
  hosts: windows
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server, Web-Common-Http
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: Download simple web site to 'C:\inetpub\wwwroot\ansible.html'
      win_get_url:
        url: 'https://raw.githubusercontent.com/thisdavejohnson/mywebapp/master/index.html'
        dest: 'C:\inetpub\wwwroot\ansible.html'